language: node_js
node_js:
  - "5"
before_script:
  - npm install -g gulp
  - chmod +x scripts/deploy.sh
script: gulp
deploy: 
skip_cleanup: true
provider: script
script: scripts/deploy.sh
on:
    branch: master